version: '3.8'

services:
  app:
    build:
      dockerfile: docker/app/Dockerfile.local
      context: .
      args:
        NODE_IMAGE: ${NODE_IMAGE}
        APP_PORT: ${APP_PORT}
    container_name: ${APP_NAME}-app
    env_file:
      - .env
    ports:
      - 3000:${APP_PORT}
    command: sh -c "npm start"
    volumes:
      - ./:/home/app
      - ./node_modules:/home/app/node_modules
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: ${DB_IMAGE}
    container_name: ${APP_NAME}-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - 5432:${DB_PORT}
    networks:
      - app_network

  minio-service:
    image: ${MINIO_IMAGE}
    container_name: ${APP_NAME}-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    ports:
      - 9000:${MINIO_PORT}
      - 9001:${MINIO_CONSOLE_PORT}
    command: minio server /data --address ":${MINIO_PORT}" --console-address ":9001"
    networks:
      - app_network

networks:
  app_network:
    name: app_network
